### ISSUE TITLE
AttributeError: ('This name is already taken', 'floatX')

### ISSUE THREAD

**Issue by oursu** [kipoi/kipoi#189]
I think this is a problem with how my Theano is set up. 

I get the following error:
```
>>> model = kipoi.get_model("rbp_eclip/UPF1")
Using Theano backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/kipoi/model.py", line 70, in get_model
    dl_source)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/kipoi/data.py", line 375, in get_dataloader_factory
    CustomDataLoader = getattr(load_module(file_path), obj_name)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/kipoi/utils.py", line 57, in load_module
    loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "dataloader.py", line 17, in <module>
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/concise/__init__.py", line 7, in <module>
    from . import layers
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/concise/layers.py", line 2, in <module>
    from keras import backend as K
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/keras/backend/__init__.py", line 81, in <module>
    from .theano_backend import *
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/keras/backend/theano_backend.py", line 7, in <module>
    import theano
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/theano/__init__.py", line 88, in <module>
    from theano.configdefaults import config
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/theano/configdefaults.py", line 47, in <module>
    in_c_key=True
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/theano/configparser.py", line 281, in AddConfigVar
    configparam.fullname)
AttributeError: ('This name is already taken', 'floatX')
```

For the installation of theano, I did:
```
conda install theano pygpu
```

Do I need to put specific things in my ~/.theanorc? At the moment, I have:
```
echo "[global]
device = cuda
floatX = float32

[lib]
cnmem = 1.0" > ~/.theanorc
``` 
as recommended here: https://github.com/leriomaggio/deep-learning-keras-tensorflow/issues/3

For the recommendation up there, I have been trying to install libgpuarray but got an error at the last step:

```
DEVICE="<test device>" /mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/bin/python -c "import pygpu;pygpu.test()"
pygpu is installed in /users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu
NumPy version 1.10.4
NumPy relaxed strides checking option: False
NumPy is installed in /mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/numpy
Python version 3.5.5 | packaged by conda-forge | (default, Feb 13 2018, 05:02:37) [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
nose version 1.3.7
EEEEEEEE
======================================================================
ERROR: Failure: ValueError (Unknown device format:<test device>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/test_basic.py", line 5, in <module>
    from .support import (gen_gpuarray, context)
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu/gpuarray.pyx", line 658, in pygpu.gpuarray.init (pygpu/gpuarray.c:9628)
  File "pygpu/gpuarray.pyx", line 581, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8974)
ValueError: Unknown device format:<test device>

======================================================================
ERROR: Failure: ValueError (Unknown device format:<test device>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/test_blas.py", line 5, in <module>
    from .support import (guard_devsup, gen_gpuarray, context)
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu/gpuarray.pyx", line 658, in pygpu.gpuarray.init (pygpu/gpuarray.c:9628)
  File "pygpu/gpuarray.pyx", line 581, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8974)
ValueError: Unknown device format:<test device>

======================================================================
ERROR: Failure: ValueError (Unknown device format:<test device>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/test_collectives.py", line 15, in <module>
    from pygpu.tests.support import (check_all, gen_gpuarray, context as ctx)
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu/gpuarray.pyx", line 658, in pygpu.gpuarray.init (pygpu/gpuarray.c:9628)
  File "pygpu/gpuarray.pyx", line 581, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8974)
ValueError: Unknown device format:<test device>

======================================================================
ERROR: Failure: ValueError (Unknown device format:<test device>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/test_elemwise.py", line 13, in <module>
    from .support import (guard_devsup, context, gen_gpuarray, check_meta_content)
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu/gpuarray.pyx", line 658, in pygpu.gpuarray.init (pygpu/gpuarray.c:9628)
  File "pygpu/gpuarray.pyx", line 581, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8974)
ValueError: Unknown device format:<test device>

======================================================================
ERROR: Failure: ValueError (Unknown device format:<test device>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/test_gpu_ndarray.py", line 15, in <module>
    from .support import (guard_devsup, check_meta, check_flags, check_all,
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu/gpuarray.pyx", line 658, in pygpu.gpuarray.init (pygpu/gpuarray.c:9628)
  File "pygpu/gpuarray.pyx", line 581, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8974)
ValueError: Unknown device format:<test device>

======================================================================
ERROR: Failure: ValueError (Unknown device format:<test device>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/test_operations.py", line 4, in <module>
    from .support import (gen_gpuarray, context, SkipTest)
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu/gpuarray.pyx", line 658, in pygpu.gpuarray.init (pygpu/gpuarray.c:9628)
  File "pygpu/gpuarray.pyx", line 581, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8974)
ValueError: Unknown device format:<test device>

======================================================================
ERROR: Failure: ValueError (Unknown device format:<test device>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/test_reduction.py", line 8, in <module>
    from .support import (guard_devsup, check_meta_content, context, gen_gpuarray,
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu/gpuarray.pyx", line 658, in pygpu.gpuarray.init (pygpu/gpuarray.c:9628)
  File "pygpu/gpuarray.pyx", line 581, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8974)
ValueError: Unknown device format:<test device>

======================================================================
ERROR: Failure: ValueError (Unknown device format:<test device>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/mnt/lab_data/kundaje/users/oursu/code/anaconda_3/mypython/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/test_tools.py", line 3, in <module>
    from .support import context, gen_gpuarray
  File "/users/oursu/.local/lib/python3.5/site-packages/pygpu-0.7.5+11.g04c2892-py3.5-linux-x86_64.egg/pygpu/tests/support.py", line 37, in <module>
    context = gpuarray.init(get_env_dev())
  File "pygpu/gpuarray.pyx", line 658, in pygpu.gpuarray.init (pygpu/gpuarray.c:9628)
  File "pygpu/gpuarray.pyx", line 581, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8974)
ValueError: Unknown device format:<test device>

----------------------------------------------------------------------
Ran 8 tests in 0.008s

FAILED (errors=8)
oursu@nandi:/users/oursu$ 
```

**Comment by Avsecz** [comment]
all models are now using tensorflow backend. closing this issue
