### ISSUE TITLE
model-template.yaml fails with reference to local files

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi#360]
Model groups defined with `model-template.yaml` and `models.tsv` fail when they refer to a local file such as `custom_model_classes.py` or even just a default_dataloader defined as `dataloader.py`.

Test the models `DeepBind_redesign` and `rbp_eclip_redesign` in the `kipoiseq_dl` branch of the models repo.

`kipoi test --source kipoi ls rbp_eclip_redesign` gives:
```
Traceback (most recent call last):
  File "/nfs/.../conda-envs/kipoi_interpret/bin/kipoi", line 11, in <module>
    load_entry_point('kipoi', 'console_scripts', 'kipoi')()
  File "/nfs/.../opt/model-zoo/kipoi/__main__.py", line 102, in main
    command_fn(args.command, sys.argv[2:])
  File "/nfs/.../opt/model-zoo/kipoi/cli/main.py", line 50, in cli_test
    mh = kipoi.get_model(args.model, args.source)
  File "/nfs/.../opt/model-zoo/kipoi/model.py", line 135, in get_model
    dl_source)
  File "/nfs/.../opt/model-zoo/kipoi/data.py", line 603, in get_dataloader
    source.pull_dataloader(dataloader)
  File "/nfs/.../opt/model-zoo/kipoi/sources.py", line 335, in pull_dataloader
    self._pull_component(dataloader, "dataloader")
  File "/nfs/.../opt/model-zoo/kipoi/sources.py", line 737, in _pull_component
    component_dir = self.local_source._get_component_dir(component, which)
  File "/nfs/.../opt/model-zoo/kipoi/sources.py", line 512, in _get_component_dir
    self.assert_is_component(component, which)
  File "/nfs/.../opt/model-zoo/kipoi/sources.py", line 328, in assert_is_component
    raise ValueError("{} {} doesn't exist".format(which, component))
ValueError: dataloader rbp_eclip_redesign/AARS doesn't exist
```
and `kipoi test --source kipoi DeepBind_redesign/Arabidopsis_thaliana/RBP/D00283.001_RNAcompete_At_0284` gives:
```
Traceback (most recent call last):
  File "/nfs/.../conda-envs/kipoi_interpret/bin/kipoi", line 11, in <module>
    load_entry_point('kipoi', 'console_scripts', 'kipoi')()
  File "/nfs/.../opt/model-zoo/kipoi/__main__.py", line 102, in main
    command_fn(args.command, sys.argv[2:])
  File "/nfs/.../opt/model-zoo/kipoi/cli/main.py", line 50, in cli_test
    mh = kipoi.get_model(args.model, args.source)
  File "/nfs/.../opt/model-zoo/kipoi/model.py", line 172, in get_model
    mod = AVAILABLE_MODELS[md.type](**md.args)
  File "/nfs/.../opt/model-zoo/kipoi/model.py", line 348, in __init__
    custom_objects=self.custom_objects)
  File "/nfs/.../conda-envs/kipoi_interpret/lib/python3.6/site-packages/keras/models.py", line 344, in model_from_json
    config = json.loads(json_string)
  File "/nfs/.../conda-envs/kipoi_interpret/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/nfs/.../conda-envs/kipoi_interpret/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nfs/.../conda-envs/kipoi_interpret/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by krrome** [comment]
all `*_redesign` models mentioned above now don't carry the `*_redesign` suffix anymore
