### ISSUE TITLE
conda error fails `deepTarget` tests

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi#361]
In the `kipoiseq_dl` branch of models repo. From circle-ci testing:

```16/18 - model: deepTarget
--------------------
INFO [kipoi.cli.env] Writing environment file: /tmp/kipoi/envfiles/b9a5595a
INFO [kipoi.cli.env] Loading model: deepTarget description
INFO [kipoi.sources] Update /root/repo/
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> kipoiseq_dl

INFO [kipoi.cli.env] Inferred dataloader name: deepTarget from the model.
INFO [kipoi.cli.env] Environment name: test-kipoi-deepTarget
INFO [kipoi.cli.env] Output env file: /tmp/kipoi/envfiles/b9a5595a/test-kipoi-deepTarget.yaml
INFO [kipoi.cli.env] Done writing the environment file!
INFO [kipoi.cli.env] Creating conda env from file: /tmp/kipoi/envfiles/b9a5595a/test-kipoi-deepTarget.yaml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/opt/conda/lib/python3.6/site-packages/conda_env/installers/conda.py", line 35, in install
        unlink_link_transaction = solver.solve_for_transaction(prune=getattr(args, 'prune', False))
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 95, in query
        self.load()
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 246, in _load
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 369, in _process_raw_repodata_str
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment

`$ /opt/conda/bin/conda-env create --file /tmp/kipoi/envfiles/b9a5595a/test-kipoi-deepTarget.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/opt/conda
                 NO_PROXY=<set>
                     PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
                          :/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.20.0 CPython/3.6.0 Linux/4.4.0-137-generic debian/8 glibc/2.19
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: 
No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

Traceback (most recent call last):
  File "/opt/conda/bin/kipoi", line 11, in <module>
Solving environment: ...working... failed
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/kipoi/__main__.py", line 102, in main
    command_fn(args.command, sys.argv[2:])
  File "/opt/conda/lib/python3.6/site-packages/kipoi/cli/env.py", line 340, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/opt/conda/lib/python3.6/site-packages/kipoi/cli/env.py", line 264, in cli_create
    kipoi.conda.create_env_from_file(env_file)
  File "/opt/conda/lib/python3.6/site-packages/kipoi/conda.py", line 78, in create_env_from_file
    return _call_conda(cmd_list, use_stdout=True)
  File "/opt/conda/lib/python3.6/site-packages/kipoi/conda.py", line 162, in _call_conda
    return _call_command("conda", extra_args, use_stdout)
  File "/opt/conda/lib/python3.6/site-packages/kipoi/conda.py", line 149, in _call_command
    raise subprocess.CalledProcessError(return_code, cmd_list)
subprocess.CalledProcessError: Command '['conda', 'env', 'create', '--file', '/tmp/kipoi/envfiles/b9a5595a/test-kipoi-deepTarget.yaml']' returned non-zero exit status 1.
ERROR [kipoi.cli.source_test] Model deepTarget failed: Command '['kipoi', 'env', 'create', '--source', 'kipoi', '--env', 'test-kipoi-deepTarget', 'deepTarget']' returned non-zero exit status 1.```

**Comment by Avsecz** [comment]
fixed this by removing `anaconda::` prefix of biopython
