### ISSUE TITLE
install_model_requirements issues

### ISSUE THREAD

**Issue by DerThorsten** [kipoi/kipoi#427]
Using kipoi in a fresh conda environment fails when I try:

 - create and activate a new conda env and install dev requirements for kipoi 
 - install kipoi  via `pip -e ....`
 - start kipoi from freshly created conda env
 - use  kipois python api to download model dependencies  (this will download the dependencies in the very  conda env I am using currently, right?) 

```python
import kipoi
kipoi.install_model_requirements(model='DeepSEA/variantEffects')
```
or
```python
import kipoi
kipoi.install_model_requirements(model='Basset')
```

fails with 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-b8eee0d73e6a> in <module>()
----> 1 kipoi.install_model_requirements(model='Basset')

~/kipoi/kipoi/pipeline.py in install_model_requirements(model, source, and_dataloaders)
     29     md.dependencies.install()
     30     if and_dataloaders:
---> 31         if ":" in md.default_dataloader:
     32             dl_source, dl_path = md.default_dataloader.split(":")
     33         else:

TypeError: argument of type 'DataLoaderImport' is not iterable
```
The same error also happens when I create a fresh conda py35 enviroment and install kipoi via pip (`pip install kipoi`).

Installing the `Basset` dependencies via CLI seems to work:
```shell
$kipoi env install Basset
....
mkl-random 1.0.1 requires cython, which is not installed.
Installing collected packages: argcomplete, argh, simplejson, gffutils, kipoiseq
Successfully installed argcomplete-1.9.4 argh-0.26.2 gffutils-0.9 kipoiseq-0.2.2 simplejson-3.16.0
You are using pip version 10.0.1, however version 19.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
INFO [kipoi.cli.env] Done!
```

But this leaves the environment in non working state:
(kipoi was installed via `pip install kipoi` in a fresh python=3.5 enviroment)
When I try to run any other kipoi CLI commands I get ImportErrors:
```python
 kipoi info Basset
Traceback (most recent call last):
  File "/home/ciclon/miniconda3/envs/pipkipoi/bin/kipoi", line 7, in <module>
    from kipoi.__main__ import main
  File "/home/ciclon/miniconda3/envs/pipkipoi/lib/python3.5/site-packages/kipoi/__init__.py", line 9, in <module>
    from . import config
  File "/home/ciclon/miniconda3/envs/pipkipoi/lib/python3.5/site-packages/kipoi/config.py", line 11, in <module>
    import pandas as pd
  File "/home/ciclon/miniconda3/envs/pipkipoi/lib/python3.5/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/ciclon/miniconda3/envs/pipkipoi/lib/python3.5/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/home/ciclon/miniconda3/envs/pipkipoi/lib/python3.5/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/home/ciclon/miniconda3/envs/pipkipoi/lib/python3.5/site-packages/pandas/core/groupby/groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "/home/ciclon/miniconda3/envs/pipkipoi/lib/python3.5/site-packages/pandas/core/frame.py", line 66, in <module>
    from pandas.core.generic import NDFrame, _shared_docs
  File "/home/ciclon/miniconda3/envs/pipkipoi/lib/python3.5/site-packages/pandas/core/generic.py", line 43, in <module>
    from pandas.core.internals import BlockManager
  File "/home/ciclon/miniconda3/envs/pipkipoi/lib/python3.5/site-packages/pandas/core/internals/__init__.py", line 2, in <module>
    from .blocks import (  # noqa:F401
  File "/home/ciclon/miniconda3/envs/pipkipoi/lib/python3.5/site-packages/pandas/core/internals/blocks.py", line 11, in <module>
    from pandas._libs.tslibs import Timedelta, conversion, is_null_datetimelike
ImportError: cannot import name 'Timedelta'
```

I guess this is due to some vwrong panda versions

**Comment by DerThorsten** [comment]
update:
 - I can use fix the `ImportError: cannot import name 'Timedelta'` by manually reinstalling pandas via pip, but reinstalling via conda does NOT worl.

- this might also also be the reason that creating `kipoi env create Basset`  works while
and `kipoi env install Basset` does not work.

**Comment by Avsecz** [comment]
Uf, that's a tricky one. Shall we remove `install_model_requirements` from our tutorials completely and suggest to use `kipoi env create ...`?

**Comment by DerThorsten** [comment]
To be precise:  The issue with `kipoi env install Basset` is related to pandas  pip/conda
For  `kipoi.install_model_requirements`  I am not yet sure, but I was wondering how this ever could work.
connsider
```python
import pandas # lets assume we have a version X < Y
import kipoi

kipoi.install_model_requirements('Basset') # assume this  will install pandas Y

# which pandas version do have have in this running script?
# X or Y or smth broken?
```

**Comment by DerThorsten** [comment]
btw: pythons  reload comes with a ton of its own problems and issues.
If kipoi.install_model_requirements relies on reload I would consider it half broken

**Comment by Avsecz** [comment]
Agree. Shall we deprecate the function?

**Comment by DerThorsten** [comment]
yup
