### ISSUE TITLE
kipoi failes to create the environment

### ISSUE THREAD

**Issue by antonkulaga** [kipoi/kipoi#476]
```
kipoi env create SeqVec/embedding
INFO [kipoi.cli.env] Writing environment file: /tmp/kipoi/envfiles/0d9435f9
INFO [kipoi.cli.env] Loading model: SeqVec/embedding description
INFO [kipoi.sources] Update /home/antonkulaga/.kipoi/models/
Already up to date.
INFO [kipoi.cli.env] Inferred dataloader name: SeqVec/embedding from the model.
INFO [kipoi.cli.env] Environment name: kipoi-SeqVec__embedding
INFO [kipoi.cli.env] Output env file: /tmp/kipoi/envfiles/0d9435f9/kipoi-SeqVec__embedding.yaml
INFO [kipoi.cli.env] Done writing the environment file!
INFO [kipoi.cli.env] Creating conda env from file: /tmp/kipoi/envfiles/0d9435f9/kipoi-SeqVec__embedding.yaml
Traceback (most recent call last):
  File "/home/antonkulaga/.local/bin/kipoi", line 10, in <module>
    sys.exit(main())
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi/cli/env.py", line 696, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi/cli/env.py", line 465, in cli_create
    env_db_entry.cli_path = get_kipoi_bin(env)
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi_conda/utils.py", line 118, in get_kipoi_bin
    raise ValueError("Conda environment {0} doesn't exist".format(env_name))
ValueError: Conda environment kipoi-SeqVec__embedding doesn't exist
```
OS - Ubuntu 19.04, conda 4.8.2

**Comment by Avsecz** [comment]
Hi, can you add `-v` to the env create command and post the error message?

**Comment by antonkulaga** [comment]
Looks like an issue with cuda configuration in the environment:
```
kipoi env create -v SeqVec/embedding
INFO [kipoi.cli.env] Writing environment file: /tmp/kipoi/envfiles/369fd182
INFO [kipoi.cli.env] Loading model: SeqVec/embedding description
INFO [kipoi.sources] Update /home/antonkulaga/.kipoi/models/
Already up to date.
INFO [kipoi.cli.env] Inferred dataloader name: SeqVec/embedding from the model.
INFO [kipoi.cli.env] Environment name: kipoi-SeqVec__embedding
INFO [kipoi.cli.env] Output env file: /tmp/kipoi/envfiles/369fd182/kipoi-SeqVec__embedding.yaml
INFO [kipoi.cli.env] Done writing the environment file!
INFO [kipoi.cli.env] Creating conda env from file: /tmp/kipoi/envfiles/369fd182/kipoi-SeqVec__embedding.yaml
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working...                                              
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Solving environment: ...working...                                              
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package _libgcc_mutex conflicts for:
python=3.6 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge']
allennlp -> libgcc-ng[version='>=4.9'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge']

Package certifi conflicts for:
pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
allennlp -> requests[version='>=2.18'] -> certifi[version='>=2017.4.17']

Package python conflicts for:
python=3.6
allennlp -> awscli[version='>=1.11.91'] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|3.4.*|2.7|>=3.4|>=3.6']
allennlp -> python[version='>=3.6,<3.7.0a0']
pip -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0|3.4.*']

Package wheel conflicts for:
python=3.6 -> pip -> wheel
pip -> wheelThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2

Note that strict channel priority may have removed packages required for satisfiability.

Traceback (most recent call last):
  File "/home/antonkulaga/.local/bin/kipoi", line 10, in <module>
    sys.exit(main())
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi/cli/env.py", line 696, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi/cli/env.py", line 461, in cli_create
    kipoi_conda.create_env_from_file(env_file, use_stdout=args.verbose)
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi_conda/utils.py", line 127, in create_env_from_file
    return _call_conda(cmd_list, use_stdout=use_stdout, dry_run=dry_run)
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi_conda/utils.py", line 196, in _call_conda
    return _call_command("conda", extra_args, use_stdout, return_logs_with_stdout, dry_run=dry_run)
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi_utils/utils.py", line 78, in _call_command
    raise Exception("could not invoke {0} \nreturn code:{1}\nadditional info:{2}".format(cmd_list, return_code, "".join(error_out)))
Exception: could not invoke ['conda', 'env', 'create', '--file', '/tmp/kipoi/envfiles/369fd182/kipoi-SeqVec__embedding.yaml'] 
return code:1
additional info:Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.Collecting package metadata (repodata.json): ...working... doneSolving environment: ...working...Found conflicts! Looking for incompatible packages.This can take several minutes.  Press CTRL-C to abort.failedSolving environment: ...working...Found conflicts! Looking for incompatible packages.This can take several minutes.  Press CTRL-C to abort.failed
```

**Comment by antonkulaga** [comment]
I have latest (10.2) CUDA installed, so I have no idea why it complains

**Comment by antonkulaga** [comment]
I managed to avoid cuda error by downgrading to CUDA 10.1, however I now have:
```
kipoi env create -v SeqVec/embedding
INFO [kipoi.cli.env] Writing environment file: /tmp/kipoi/envfiles/2b34dc23
INFO [kipoi.cli.env] Loading model: SeqVec/embedding description
INFO [kipoi.sources] Update /home/antonkulaga/.kipoi/models/
Already up to date.
INFO [kipoi.cli.env] Inferred dataloader name: SeqVec/embedding from the model.
INFO [kipoi.cli.env] Environment name: kipoi-SeqVec__embedding
INFO [kipoi.cli.env] Output env file: /tmp/kipoi/envfiles/2b34dc23/kipoi-SeqVec__embedding.yaml
INFO [kipoi.cli.env] Done writing the environment file!
INFO [kipoi.cli.env] Creating conda env from file: /tmp/kipoi/envfiles/2b34dc23/kipoi-SeqVec__embedding.yaml
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Traceback (most recent call last):
  File "/home/antonkulaga/.local/bin/kipoi", line 10, in <module>
    sys.exit(main())
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi/cli/env.py", line 696, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi/cli/env.py", line 461, in cli_create
    kipoi_conda.create_env_from_file(env_file, use_stdout=args.verbose)
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi_conda/utils.py", line 127, in create_env_from_file
    return _call_conda(cmd_list, use_stdout=use_stdout, dry_run=dry_run)
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi_conda/utils.py", line 196, in _call_conda
    return _call_command("conda", extra_args, use_stdout, return_logs_with_stdout, dry_run=dry_run)
  File "/home/antonkulaga/.local/lib/python3.7/site-packages/kipoi_utils/utils.py", line 78, in _call_command
    raise Exception("could not invoke {0} \nreturn code:{1}\nadditional info:{2}".format(cmd_list, return_code, "".join(error_out)))
Exception: could not invoke ['conda', 'env', 'create', '--file', '/tmp/kipoi/envfiles/2b34dc23/kipoi-SeqVec__embedding.yaml'] 
return code:-11
additional info:Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.Collecting package metadata (repodata.json): ...working... doneSolving environment: ...working... done
```
@Avsecz could you tell me what does it mean?

**Comment by Avsecz** [comment]
Hm. That's really weird. Can you share /tmp/kipoi/envfiles/2b34dc23/kipoi-SeqVec__embedding.yaml?

Also, can you try manually installing this conda environment using ` cona env create -f /tmp/kipoi/envfiles/2b34dc23/kipoi-SeqVec__embedding.yaml`
