### ISSUE TITLE
AttributeError: module 'kipoi' has no attribute 'list_model'

### ISSUE THREAD

**Issue by ashea2nd** [kipoi/kipoi#500]
Hi there, 

I'm having issues getting kipoi to work on my machine. I'm using Ubuntu 16.04 and installed kipoi using 'pip install kipoi.'

There seems to be an issue with how this package is being imported, but I'm having trouble understanding if its an issue on my end or the library's. 

Thanks

![Screen Shot 2020-06-05 at 11 48 05 PM (2)](https://user-images.githubusercontent.com/18687568/83935388-2e740380-a787-11ea-839c-2123381972e7.png)

**Comment by Avsecz** [comment]
Cam you try with python 3.6?

**Comment by ashea2nd** [comment]
I got the same error

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
	import kipoi
  File "/data1/andrew/meng/summer/env36/lib/python3.6/site-packages/kipoi/__init__.py", line 11, in <module>
	from . import pipeline
  File "/data1/andrew/meng/summer/env36/lib/python3.6/site-packages/kipoi/pipeline.py", line 9, in <module>
	from .data import numpy_collate_concat
  File "/data1/andrew/meng/summer/env36/lib/python3.6/site-packages/kipoi/data.py", line 13, in <module>
	import related
  File "/data1/andrew/meng/summer/env36/lib/python3.6/site-packages/related/__init__.py", line 16, in <module>
	from .fields import (
  File "/data1/andrew/meng/summer/env36/lib/python3.6/site-packages/related/fields.py", line 3, in <module>
	from future.moves.urllib.parse import ParseResult
  File "/data1/andrew/meng/summer/env36/lib/python3.6/site-packages/future/moves/__init__.py", line 8, in <module>
	import_top_level_modules()
  File "/data1/andrew/meng/summer/env36/lib/python3.6/site-packages/future/standard_library/__init__.py", line 810, in import_top_level_modules
	with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "/data1/andrew/meng/summer/env36/lib/python3.6/site-packages/future/standard_library/__init__.py", line 781, in __enter__
	module = __import__(m, level=0)
  File "/data1/andrew/meng/summer/project/test.py", line 6, in <module>
	p(kipoi.list_models())
AttributeError: module 'kipoi' has no attribute 'list_models'

```

**Comment by Avsecz** [comment]
Thanks! I will try to fix that over the weekend.
