### ISSUE TITLE
failed to import kipoi when executing python script in terminal

### ISSUE THREAD

**Issue by TzuTingWei** [kipoi/kipoi#534]
I wrote a python script to run deepsea model and get the prediction scores, and I ran it as `python script.py` in the terminal in the conda environment _kipoi-DeepSEA__variantEffects_. However, I received an AttributeError as in the screenshot:  

![image](https://user-images.githubusercontent.com/11897598/91871436-854e8380-ec77-11ea-9e22-0b29bce8c871.png)

The kipoi version I am using:
```
kipoi                     0.6.29                   pypi_0    pypi
kipoi-conda               0.2.2                    pypi_0    pypi
kipoi-utils               0.3.8                    pypi_0    pypi
kipoi-veff                0.3.1                    pypi_0    pypi
```

The minimal script (test.py) to reproduce the bug:
```
#!/usr/bin/env python
import kipoi
import kipoi_veff.snv_predict as sp
from kipoi_veff.parsers import KipoiVCFParser
```

I have checked the python version and they are pointed at the same path. There is no pkg/file/folder with the same name. I also moved the file to the folder or other subfolder, the error behaviours are the same.

**Comment by Hoeze** [comment]
I was able to reproduce. Could this be related to the `pydoc-md` update?
@haimasree Would you have time to have a look?

Copyable error log:
<details>

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import kipoi
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/kipoi/__init__.py", line 10, in <module>
    from . import config
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/kipoi/config.py", line 180, in <module>
    for k, v in six.iteritems(_model_sources)])
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/kipoi/config.py", line 180, in <listcomp>
    for k, v in six.iteritems(_model_sources)])
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/kipoi/sources.py", line 881, in load_source
    return cls.from_config(config)
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/kipoi/sources.py", line 438, in from_config
    return cls(**config)
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/kipoi/sources.py", line 632, in __init__
    self.local_source = LocalSource(self.local_path, name=name)
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/kipoi/sources.py", line 469, in __init__
    from kipoi.specs import SourceConfig
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/kipoi/specs.py", line 13, in <module>
    import related
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/related/__init__.py", line 16, in <module>
    from .fields import (
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/related/fields.py", line 3, in <module>
    from future.moves.urllib.parse import ParseResult
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/future/moves/__init__.py", line 8, in <module>
    import_top_level_modules()
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/future/standard_library/__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/future/standard_library/__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "/data/nasif12/home_if12/hoelzlwi/test.py", line 2, in <module>
    import kipoi_veff.snv_predict as sp
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/kipoi_veff/__init__.py", line 8, in <module>
    from . import scores
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/kipoi_veff/scores.py", line 12, in <module>
    from kipoi_veff.specs import VarEffectFuncType
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/kipoi_veff/specs.py", line 26, in <module>
    class VarEffectScoringFuncArgument(RelatedConfigMixin):
  File "/opt/modules/i12g/anaconda/envs/kipoi-DeepSEA__variantEffects/lib/python3.7/site-packages/kipoi_veff/specs.py", line 28, in VarEffectScoringFuncArgument
    doc = related.StringField("", required=False)
AttributeError: module 'related' has no attribute 'StringField'
```

</details>

**Comment by haimasree** [comment]
@TzuTingWei  
Okay I am not exactly sure what is the problem yet, but try renaming test to say test_script or test1 and see if you are still getting the error.

**Comment by haimasree** [comment]
@TzuTingWei
Another solution would be to keep the name as it is but make sure to import kipoi after you have imported from kipoi veff like so -
```
import kipoi_veff.snv_predict as sp
import kipoi
```

**Comment by haimasree** [comment]
@TzuTingWei  
Another solution: I am not exactly sure what is the problem yet, but try renaming test.py to say test_script.py or test1.py and see if you are still getting the error.

**Comment by TzuTingWei** [comment]
@haimasree 
Rename the test script didn't work but the reordering of import actually did not cause the error anymore. Thank you! 
May I ask why the import order actually matters that much?
