### ISSUE TITLE
Error in "kipoi env create KipoiSplice/4" 

### ISSUE THREAD

**Issue by LIKUOKUO** [kipoi/kipoi#623]
**When I run "kipoi env create KipoiSplice/4", it return error as follow:**

fatal: unable to access 'https://github.com/kipoi/models.git/': Encountered end of file
Pip subprocess error:
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/related/
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8970314080>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/42/ec/32310181e803f5d22e0dd33eb18924489b2f8d08cf5b6e116a93a6a5d1c6/scikit_learn-0.22.2.post1-cp35-cp35m-manylinux1_x86_64.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8970314f28>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/42/ec/32310181e803f5d22e0dd33eb18924489b2f8d08cf5b6e116a93a6a5d1c6/scikit_learn-0.22.2.post1-cp35-cp35m-manylinux1_x86_64.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f89703149b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /packages/42/ec/32310181e803f5d22e0dd33eb18924489b2f8d08cf5b6e116a93a6a5d1c6/scikit_learn-0.22.2.post1-cp35-cp35m-manylinux1_x86_64.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 321, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/resolvelib/resolvers.py", line 339, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 172, in get_dependencies
    for r in candidate.iter_dependencies(with_requires)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 171, in <listcomp>
    r
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 257, in iter_dependencies
    requires = self.dist.requires() if with_requires else ()
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 319, in _prepare_distribution
    self._ireq, parallel_builds=True,
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 505, in _prepare_linked_requirement
    self.download_dir, hashes,
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 257, in unpack_url
    hashes=hashes,
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 130, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/network/download.py", line 163, in __call__
    for chunk in chunks:
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/cli/progress_bars.py", line 168, in iter
    for x in it:
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/network/utils.py", line 88, in response_chunks
    decode_content=False,
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

CondaEnvException: Pip failed

Traceback (most recent call last):
  File "/root/miniconda3/bin/kipoi", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.7/site-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/root/miniconda3/lib/python3.7/site-packages/kipoi/cli/env.py", line 696, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/root/miniconda3/lib/python3.7/site-packages/kipoi/cli/env.py", line 461, in cli_create
    kipoi_conda.create_env_from_file(env_file, use_stdout=args.verbose)
  File "/root/miniconda3/lib/python3.7/site-packages/kipoi_conda/utils.py", line 127, in create_env_from_file
    return _call_conda(cmd_list, use_stdout=use_stdout, dry_run=dry_run)
  File "/root/miniconda3/lib/python3.7/site-packages/kipoi_conda/utils.py", line 196, in _call_conda
    return _call_command("conda", extra_args, use_stdout, return_logs_with_stdout, dry_run=dry_run)
  File "/root/miniconda3/lib/python3.7/site-packages/kipoi_utils/utils.py", line 78, in _call_command
    raise Exception("could not invoke {0} \nreturn code:{1}\nadditional info:{2}".format(cmd_list, return_code, "".join(error_out)))
Exception: could not invoke ['conda', 'env', 'create', '--file', '/tmp/kipoi/envfiles/ccb72598/kipoi-KipoiSplice__4.yaml']
return code:1
additional info:Collecting package metadata (repodata.json): ...working... doneSolving environment: ...working... donePreparing transaction: ...working... doneVerifying transaction: ...working... doneExecuting transaction: ...working... doneInstalling pip dependencies: ...working... Ran pip subprocess with arguments:['/root/miniconda3/envs/kipoi-KipoiSplice__4/bin/python', '-m', 'pip', 'install', '-U', '-r', '/tmp/kipoi/envfiles/ccb72598/condaenv.mhmd1zw0.requirements.txt']Pip subprocess output:Collecting keras==2.2.4  Using cached Keras-2.2.4-py2.py3-none-any.whl (312 kB)Requirement already satisfied: numpy>=1.9.1 in /root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages (from keras==2.2.4->-r /tmp/kipoi/envfiles/ccb72598/condaenv.mhmd1zw0.requirements.txt (line 10)) (1.15.2)Requirement already satisfied: six>=1.9.0 in /root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages (from keras==2.2.4->-r /tmp/kipoi/envfiles/ccb72598/condaenv.mhmd1zw0.requirements.txt (line 10)) (1.16.0)Requirement already satisfied: h5py in /root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages (from keras==2.2.4->-r /tmp/kipoi/envfiles/ccb72598/condaenv.mhmd1zw0.requirements.txt (line 10)) (2.8.0)Collecting kipoi==0.6.30  Using cached kipoi-0.6.30-py3-none-any.whl (101 kB)Requirement already satisfied: pandas>=0.21.0 in /root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages (from kipoi==0.6.30->-r /tmp/kipoi/envfiles/ccb72598/condaenv.mhmd1zw0.requirements.txt (line 1)) (0.23.4)Collecting scikit-learn==0.22.2.post1  Downloading scikit_learn-0.22.2.post1-cp35-cp35m-manylinux1_x86_64.whl (7.0 MB)failed

**Comment by LIKUOKUO** [comment]
My OS was CentOS Linux release 7.9.2009 (Core)

I run the code "kipoi env create KipoiSplice/4 --verbose". All results are  as follow:

From https://github.com/kipoi/models
 * branch            HEAD       -> FETCH_HEAD
Already up-to-date.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Pip subprocess error:
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
ERROR: Exception:
Traceback (most recent call last):
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 321, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/resolvelib/resolvers.py", line 339, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 172, in get_dependencies
    for r in candidate.iter_dependencies(with_requires)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 171, in <listcomp>
    r
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 257, in iter_dependencies
    requires = self.dist.requires() if with_requires else ()
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 319, in _prepare_distribution
    self._ireq, parallel_builds=True,
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 505, in _prepare_linked_requirement
    self.download_dir, hashes,
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 257, in unpack_url
    hashes=hashes,
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 130, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/network/download.py", line 163, in __call__
    for chunk in chunks:
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/cli/progress_bars.py", line 168, in iter
    for x in it:
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_internal/network/utils.py", line 88, in response_chunks
    decode_content=False,
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

Installing pip dependencies: ...working... Ran pip subprocess with arguments:
['/root/miniconda3/envs/kipoi-KipoiSplice__4/bin/python', '-m', 'pip', 'install', '-U', '-r', '/tmp/kipoi/envfiles/09eef4b2/condaenv.1u3xsw0h.requirements.txt']
Pip subprocess output:
Collecting keras==2.2.4
  Using cached Keras-2.2.4-py2.py3-none-any.whl (312 kB)
Requirement already satisfied: numpy>=1.9.1 in /root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages (from keras==2.2.4->-r /tmp/kipoi/envfiles/09eef4b2/condaenv.1u3xsw0h.requirements.txt (line 10)) (1.15.2)
Requirement already satisfied: six>=1.9.0 in /root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages (from keras==2.2.4->-r /tmp/kipoi/envfiles/09eef4b2/condaenv.1u3xsw0h.requirements.txt (line 10)) (1.16.0)
Requirement already satisfied: h5py in /root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages (from keras==2.2.4->-r /tmp/kipoi/envfiles/09eef4b2/condaenv.1u3xsw0h.requirements.txt (line 10)) (2.8.0)
Collecting kipoi==0.6.30
  Using cached kipoi-0.6.30-py3-none-any.whl (101 kB)
Requirement already satisfied: pandas>=0.21.0 in /root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages (from kipoi==0.6.30->-r /tmp/kipoi/envfiles/09eef4b2/condaenv.1u3xsw0h.requirements.txt (line 1)) (0.23.4)
Collecting scikit-learn==0.22.2.post1
  Downloading scikit_learn-0.22.2.post1-cp35-cp35m-manylinux1_x86_64.whl (7.0 MB)

failed

CondaEnvException: Pip failed

Traceback (most recent call last):
  File "/root/miniconda3/bin/kipoi", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.7/site-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/root/miniconda3/lib/python3.7/site-packages/kipoi/cli/env.py", line 696, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/root/miniconda3/lib/python3.7/site-packages/kipoi/cli/env.py", line 461, in cli_create
    kipoi_conda.create_env_from_file(env_file, use_stdout=args.verbose)
  File "/root/miniconda3/lib/python3.7/site-packages/kipoi_conda/utils.py", line 127, in create_env_from_file
    return _call_conda(cmd_list, use_stdout=use_stdout, dry_run=dry_run)
  File "/root/miniconda3/lib/python3.7/site-packages/kipoi_conda/utils.py", line 196, in _call_conda
    return _call_command("conda", extra_args, use_stdout, return_logs_with_stdout, dry_run=dry_run)
  File "/root/miniconda3/lib/python3.7/site-packages/kipoi_utils/utils.py", line 78, in _call_command
    raise Exception("could not invoke {0} \nreturn code:{1}\nadditional info:{2}".format(cmd_list, return_code, "".join(error_out)))
Exception: could not invoke ['conda', 'env', 'create', '--file', '/tmp/kipoi/envfiles/09eef4b2/kipoi-KipoiSplice__4.yaml']
return code:1
additional info:Collecting package metadata (repodata.json): ...working... doneSolving environment: ...working... donePreparing transaction: ...working... doneVerifying transaction: ...working... doneExecuting transaction: ...working... doneInstalling pip dependencies: ...working... Ran pip subprocess with arguments:['/root/miniconda3/envs/kipoi-KipoiSplice__4/bin/python', '-m', 'pip', 'install', '-U', '-r', '/tmp/kipoi/envfiles/09eef4b2/condaenv.1u3xsw0h.requirements.txt']Pip subprocess output:Collecting keras==2.2.4  Using cached Keras-2.2.4-py2.py3-none-any.whl (312 kB)Requirement already satisfied: numpy>=1.9.1 in /root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages (from keras==2.2.4->-r /tmp/kipoi/envfiles/09eef4b2/condaenv.1u3xsw0h.requirements.txt (line 10)) (1.15.2)Requirement already satisfied: six>=1.9.0 in /root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages (from keras==2.2.4->-r /tmp/kipoi/envfiles/09eef4b2/condaenv.1u3xsw0h.requirements.txt (line 10)) (1.16.0)Requirement already satisfied: h5py in /root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages (from keras==2.2.4->-r /tmp/kipoi/envfiles/09eef4b2/condaenv.1u3xsw0h.requirements.txt (line 10)) (2.8.0)Collecting kipoi==0.6.30  Using cached kipoi-0.6.30-py3-none-any.whl (101 kB)Requirement already satisfied: pandas>=0.21.0 in /root/miniconda3/envs/kipoi-KipoiSplice__4/lib/python3.5/site-packages (from kipoi==0.6.30->-r /tmp/kipoi/envfiles/09eef4b2/condaenv.1u3xsw0h.requirements.txt (line 1)) (0.23.4)Collecting scikit-learn==0.22.2.post1  Downloading scikit_learn-0.22.2.post1-cp35-cp35m-manylinux1_x86_64.whl (7.0 MB)failed

**Comment by haimasree** [comment]
Sorry I dont have access to this particular os. From the stacktrace it seems you have trouble downloading scikit_learn-0.22.2.post1-cp35-cp35m-manylinux1_x86_64.whl. scikit-learn0.22.2post1 is required to run KipoiSplice/4.  Is it possible to use a docker or a singularity container? For information about how to use the docker container please check [here](http://kipoi.org/models/KipoiSplice/4/).

 For singularity, try:
```
singularity pull docker://haimasree/kipoi-docker:kipoisplice
```
This will produce a .sif file which you can use with singularity exec.

Let me know

**Comment by LIKUOKUO** [comment]
I try used the docker to run  kipoisplice. I install docker and get the docker image by run "docker pull haimasree/kipoi-docker:kipoisplice".  I creat the directionary by the code "mkdir -p $PWD/kipoi-example". 
But when I run "docker run -v $PWD/kipoi-example:/app/ haimasree/kipoi-docker:kipoisplice  kipoi get-example KipoiSplice/4 -o /app/example". 

It return "fatal: unable to access 'https://github.com/kipoi/models.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
Traceback (most recent call last):
  File "/opt/conda/envs/kipoi-KipoiSplice/bin/kipoi", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/kipoi-KipoiSplice/lib/python3.5/site-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/opt/conda/envs/kipoi-KipoiSplice/lib/python3.5/site-packages/kipoi/cli/main.py", line 143, in cli_get_example
    kwargs = dl_descr.download_example(output_dir=args.output, dry_run=False)
  File "/opt/conda/envs/kipoi-KipoiSplice/lib/python3.5/site-packages/kipoi/specs.py", line 1002, in download_example
    dry_run=dry_run)
  File "/opt/conda/envs/kipoi-KipoiSplice/lib/python3.5/site-packages/kipoi/specs.py", line 912, in example_kwargs
    os.makedirs(dl_dir)
  File "/opt/conda/envs/kipoi-KipoiSplice/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app/example'"

**Comment by haimasree** [comment]
Unfortunately I cannot reproduce this error either but I have a few things for you to check out

- [ ] Do you have read/write access to ~/.kipoi/models? What do you see if you do ```ls ~/.kipoi/models/KipoiSplice/4?```. I am assuming you have not changed anything in ~/kipoi/config.yaml
- [ ] Do you have write access to $PWD/kipoi-example? ```-v``` is mapping $PWD/kipoi-example to /app inside the docker container. So, if you are getting ```Permission denied: '/app/example'"``` first we should check if you have permission to create and write into folder called ```example``` by ```kipoi get-example KipoiSplice/4 -o /app/example```

**Comment by haimasree** [comment]
Perhaps it would be easier to just copy the entire command using the copy button?
![image](https://user-images.githubusercontent.com/31005140/136174200-e56cd995-afa6-4c52-8cbd-1b2c97a7f326.png)

**Comment by haimasree** [comment]
I have one more thought - First create a conda environment with python 3.5 in you system.
```
conda create -n py35 python=3.5
conda activate py35
```
Now  can you try doing the following?
```pip install scikit-learn==0.22.2.post1``` since it seems like it is the main problem. If not can you check if you can install ```pip install scikit-learn==0.22.1``` inside the same environment?

**Comment by haimasree** [comment]
From your stack trace it seems it is coming from MaxEntScan model and untimately [pysam:303](https://github.com/pysam-developers/pysam/blob/master/pysam/libcfaidx.pyx#L303) I googled this error and found these two threads for very similar errors

https://github.com/nanoporetech/medaka/issues/193
https://github.com/malonge/RagTag/issues/14

I did not have much time to go through this in detail but it seemed pysam versions and/or inconsistency between your gtf and fasta files are two most likely culprits. 

I also noticed your conda environment is using python 3.7 as opposed to 3.5 as specified [here](https://github.com/kipoi/models/blob/master/KipoiSplice/4/dataloader.yaml#L37). pysam version inside the docker container is 0.15.2. I cant say for certain but an upgraded pysam version may not stay compatible with KipoiSplice. Perhsps check you pysam version as well?

Hope this helps.
