### ISSUE TITLE
A question on model submission. 

### ISSUE THREAD

**Issue by okurman** [kipoi/kipoi#674]
Hi guys! 

I'm sorry, I couldn't find a more suitable category for my question so posting it under the Bugs tag. 

I am trying to upload a set of models to the Kipoi system but couldn't find information on what I'm looking for. 
Namely, let's say I have two models: m_A and m_B. 
m_A is a standalone model, and there's no problem with it, the `kipoi test`  runs fine. 
But for m_B, I need to have a script for the input loader such that its input is generated using m_A. 
Is there a way to do that? 

Apologies in advance if this information is available on the website and I've missed it. 

Thanks!
Sanjar.

**Comment by haimasree** [comment]
Hi Sanjar,
      Thanks for trying out kipoi. I think, yhe only model (group) that resembles your description is [SeqVec](https://github.com/kipoi/models/tree/master/SeqVec). If you look at [structure](https://github.com/kipoi/models/blob/7afe5317d0e213ddefc3a031497e5f5eee8ca5b1/SeqVec/structure/model.py#L16-L17), `self.struct` seems to be doing what you are describing - using `embedding` models' inference predictions from [here](https://github.com/kipoi/models/blob/7afe5317d0e213ddefc3a031497e5f5eee8ca5b1/SeqVec/embedding/model.py#L28-L92). Not sure if this helps at all.

Let me know!

**Comment by okurman** [comment]
Thanks @haimasree,

I have another problem now. I replaced my python2 based conda with python3 based conda, but now there's this error, does it say anything to you?

I made sure to have the kipoiseq module installed separately... 

> Traceback (most recent call last):
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/kipoi_utils/utils.py", line 134, in load_obj
    module = importlib.import_module(module_name)
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/kipoiseq/__init__.py", line 11, in <module>
    from . import dataloaders
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/kipoiseq/dataloaders/__init__.py", line 1, in <module>
    from .sequence import *
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/kipoiseq/dataloaders/sequence.py", line 3, in <module>
    import pyranges as pr
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/pyranges/__init__.py", line 137, in <module>
    import pyranges.genomicfeatures as gf
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/pyranges/genomicfeatures.py", line 7, in <module>
    from sorted_nearest.src.introns import find_introns
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/sorted_nearest/__init__.py", line 7, in <module>
    from sorted_nearest.src.k_nearest_ties import get_all_ties, get_different_ties
ImportError: cannot import name 'get_all_ties' from 'sorted_nearest.src.k_nearest_ties' (/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/sorted_nearest/src/k_nearest_ties.cpython-39-x86_64-linux-gnu.so)

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/kipoi_utils/utils.py", line 140, in load_obj
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/panfs/pan1.be-md.ncbi.nlm.nih.gov/devdcode/sanjar/TREDNet/kipoi/TREDNet/phase_one/kipoiseq.py'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/panfs/pan1/devdcode/sanjar/miniconda3/bin/kipoi", line 8, in <module>
    sys.exit(main())
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/kipoi/__main__.py", line 107, in main
    command_fn(args.command, sys.argv[2:])
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/kipoi/cli/main.py", line 69, in cli_test
    mh = kipoi.get_model(args.model, args.source)
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/kipoi/model.py", line 125, in get_model
    default_dataloader = md.default_dataloader.get()
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/kipoi/specs.py", line 805, in get
    obj = load_obj(self.defined_as)
  File "/panfs/pan1/devdcode/sanjar/miniconda3/lib/python3.9/site-packages/kipoi_utils/utils.py", line 143, in load_obj
    raise ImportError("object {} couldn't be imported. Error {}".format(obj_import, str(e)))
ImportError: object kipoiseq.dataloaders.SeqIntervalDl couldn't be imported. Error [Errno 2] No such file or directory: '/panfs/pan1.be-md.ncbi.nlm.nih.gov/devdcode/sanjar/TREDNet/kipoi/TREDNet/phase_one/kipoiseq.py'

**Comment by haimasree** [comment]
Yes this is due to a broken new release of a 3rd party library called sorted-nearest used by kipoiseq. I have already made an issue [here](https://github.com/kipoi/kipoiseq/issues/109) and provided a fix [here](https://github.com/kipoi/kipoiseq/pull/110).  kipoiseq maintainer told me he will have a look at it in a week and will made a new pypi release of kipoiseq. In the meantime you can do the following inside your conda environment -

```
pip install sorted-nearest==0.0.33
```

If you are having trouble with protobuf (some kipoi models did recently) make sure to do the following as well -

```
pip install sorted-nearest==3.20 (if python>=3.6, otherwise 3.19.4)
```

**Comment by okurman** [comment]
Thanks a lot, that helped! 

Now back to my original question: 

- From the structures of the directories of SeqVec, I see that there are model.py files in the directories of each model. Does it mean that we can manually create them? If so, what should be the interface for making predictions using that model, inside the model.py module? For instance, in SeqVec's case, the `structure/model.py` and `embedding/model.py` do not have standardized interfaces. 

- As I am following the Getting Started page, in the "Forking and Submitting" section it instructs me the submit the root directory of the models to GitHub, which would also include big model weight files. From what I see, the directories of other models on the GitHub models page do not contain the weight and model files either ... am I missing something?

**Comment by haimasree** [comment]
Yes I left a review. Please resubmit with the changes I requested. 
For bookkeeping, is it okay then if I close this issue? It would be fine too if you would like to keep it open until your pr is merged.

**Comment by okurman** [comment]
Yes sure, either way, is fine with me. I'm addressing the problem with the push now.

**Comment by haimasree** [comment]
Closing since this has been resiolved by https://github.com/kipoi/models/pull/330
